### ISSUE TITLE
Research on email providers and configure the email sending in "Contact us" form.

### ISSUE THREAD

**Issue by Fdreyr** [nexoapex/www#5]
Do some research on providers (princing, features...)

eg: 
- airform: (https://airform.io/#getting-started)
  - free from now.
- mailgun: https://www.mailgun.com/es/
- herotofu: https://herotofu.com/
-

**Comment by SilverNowaru** [comment]
I made a branch that uses the suggested contact form API according to the "params.toml" file, in this case airform, it's free and doesn't seem to have a submission limit so it should be fine for our needs, but there are still alternatives should the need arise.
